"""
                      [TeamDev](https://team_x_og)
          
          Project Id -> 28.
          Project Name -> Script Host.
          Project Age -> 4Month+ (Updated On 07/03/2026)
          Project Idea By -> @MR_ARMAN_08
          Project Dev -> @MR_ARMAN_08
          Powered By -> @Team_X_Og ( On Telegram )
          Updates -> @CrimeZone_Update ( On telegram )
    
    Setup Guides -> Read > README.md Or VPS_README.md
    
          This Script Part Off https://Team_X_Og's Team.
          Copyright ©️ 2026 TeamDev | @Team_X_Og
          
    • Some Quick Help
    - Use In Vps Other Way This Bot Won't Work.
    - If You Need Any Help Contact Us In @Team_X_Og's Group
    
         Compatible In BotApi 9.5 Fully
         Build For BotApi 9.4
         We'll Keep Update This Repo If We Got 50+ Stars In One Month Of Release.
"""



"""
import os
import subprocess
import shutil
import zipfile
import tempfile
import re
import threading
from datetime import datetime

SITES_BASE_DIR  = "/var/www/hosted_sites"
NGINX_AVAIL_DIR = "/etc/nginx/sites-available"
NGINX_SITES_DIR = "/etc/nginx/sites-enabled"
CERTBOT_EMAIL   = "YOUR_GMAIL@gmail.com"
BOT_DOMAIN      = "YOUR_DOMAIN"

WILDCARD_CERT = "/etc/letsencrypt/live/YOUR_DOMAIN-0001/fullchain.pem"
WILDCARD_KEY  = "/etc/letsencrypt/live/YOUR_DOMAIN-0001/privkey.pem"

WEBSITE_LIMITS = {
    "Premium": {
        "max_websites":  3,
        "max_size_mb":   500,
        "custom_domain": True,
        "ssl":           True,
        "bandwidth_gb":  100,
        "tier":          "Premium",
    },
    "Free": {
        "max_websites":  1,
        "max_size_mb":   50,
        "custom_domain": False,
        "ssl":           True,
        "bandwidth_gb":  5,
        "tier":          "Free",
    },
}


def get_website_limits(is_premium: bool) -> dict:
    return WEBSITE_LIMITS["Premium"] if is_premium else WEBSITE_LIMITS["Free"]

def _run(cmd: str, timeout: int = 60):
    try:
        r = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=timeout)
        return r.returncode == 0, (r.stdout + r.stderr).strip()
    except subprocess.TimeoutExpired:
        return False, "Command timed out"
    except Exception as e:
        return False, str(e)


def _safe_name(name: str) -> str:
    return re.sub(r"[^a-z0-9\-]", "-", name.lower()).strip("-")[:40]


def _ensure_dirs():
    for d in [SITES_BASE_DIR, NGINX_AVAIL_DIR, NGINX_SITES_DIR]:
        os.makedirs(d, exist_ok=True)

def _nginx_subdomain_config(subdomain: str, site_dir: str) -> str:
    return f"""# Auto-generated by TeamDev Host Bot
server {{
    listen 80;
    server_name {subdomain};
    return 301 https://$host$request_uri;
}}

server {{
    listen 443 ssl http2;
    server_name {subdomain};
    root {site_dir};
    index index.html index.htm;

    ssl_certificate     {WILDCARD_CERT};
    ssl_certificate_key {WILDCARD_KEY};
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    add_header Strict-Transport-Security "max-age=63072000" always;
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header X-XSS-Protection "1; mode=block";

    location / {{
        try_files $uri $uri/ /index.html =404;
    }}

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml image/svg+xml;

    access_log /var/log/nginx/{subdomain}.access.log;
    error_log  /var/log/nginx/{subdomain}.error.log;
}}
"""


def _nginx_custom_domain_config(custom_domain: str, site_dir: str,
                                 ssl: bool = False, cert: str = None, key: str = None) -> str:
    if not ssl:
        return f"""server {{
    listen 80;
    server_name {custom_domain};
    root {site_dir};
    index index.html index.htm;
    location / {{ try_files $uri $uri/ /index.html =404; }}
    gzip on;
    access_log /var/log/nginx/{custom_domain}.access.log;
    error_log  /var/log/nginx/{custom_domain}.error.log;
}}
"""
    return f"""server {{
    listen 80;
    server_name {custom_domain};
    return 301 https://$host$request_uri;
}}

server {{
    listen 443 ssl http2;
    server_name {custom_domain};
    root {site_dir};
    index index.html index.htm;

    ssl_certificate     {cert};
    ssl_certificate_key {key};
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    add_header Strict-Transport-Security "max-age=63072000" always;
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    location / {{ try_files $uri $uri/ /index.html =404; }}
    gzip on;
    access_log /var/log/nginx/{custom_domain}.access.log;
    error_log  /var/log/nginx/{custom_domain}.error.log;
}}
"""


def _write_nginx(config_name: str, content: str):
    avail  = os.path.join(NGINX_AVAIL_DIR, config_name)
    linked = os.path.join(NGINX_SITES_DIR, config_name)
    with open(avail, "w") as f:
        f.write(content)
    if not os.path.islink(linked):
        os.symlink(avail, linked)


def _remove_nginx(config_name: str):
    for path in [os.path.join(NGINX_SITES_DIR, config_name),
                 os.path.join(NGINX_AVAIL_DIR, config_name)]:
        if os.path.islink(path) or os.path.exists(path):
            try: os.unlink(path)
            except: pass


def _reload_nginx():
    ok, out = _run("sudo /usr/sbin/nginx -t")
    if not ok:
        return False, f"Nginx config test failed:\n{out}"
    return _run("sudo /bin/systemctl reload nginx")

def ensure_website_collection(db):
    if "websites" not in db.db.list_collection_names():
        db.db.create_collection("websites")
    col = db.db["websites"]
    col.create_index("user_id")
    col.create_index("site_name", unique=True)
    col.create_index("custom_domain", sparse=True)


def get_user_websites(db, user_id: int) -> list:
    return list(db.db["websites"].find({"user_id": user_id}))


def get_website(db, site_name: str):
    return db.db["websites"].find_one({"site_name": site_name})


def count_user_websites(db, user_id: int) -> int:
    return db.db["websites"].count_documents({"user_id": user_id})


def create_website_record(db, user_id: int, site_name: str, subdomain: str,
                           site_dir: str, tier: str) -> str:
    doc = {
        "user_id":       user_id,
        "site_name":     site_name,
        "subdomain":     subdomain,
        "site_dir":      site_dir,
        "custom_domain": None,
        "ssl_enabled":   True,
        "custom_ssl":    False,
        "status":        "active",
        "tier":          tier,
        "created_at":    datetime.now(),
        "updated_at":    datetime.now(),
    }
    return str(db.db["websites"].insert_one(doc).inserted_id)


def update_website_record(db, site_name: str, update: dict):
    db.db["websites"].update_one(
        {"site_name": site_name},
        {"$set": {**update, "updated_at": datetime.now()}}
    )


def delete_website_record(db, site_name: str):
    db.db["websites"].delete_one({"site_name": site_name})

def deploy_website(db, user_id: int, zip_path: str, project_name: str,
                   is_premium: bool, progress_cb=None) -> dict:
    limits    = get_website_limits(is_premium)
    site_name = _safe_name(project_name)

    base, suffix = site_name, 1
    while get_website(db, site_name):
        site_name = f"{base}-{suffix}"; suffix += 1

    subdomain = f"{site_name}.{BOT_DOMAIN}"
    site_dir  = os.path.join(SITES_BASE_DIR, site_name)

    try:
        _ensure_dirs()
        if progress_cb: progress_cb("📦 Extracting files...")

        with tempfile.TemporaryDirectory() as tmp:
            with zipfile.ZipFile(zip_path, "r") as z:
                total = sum(i.file_size for i in z.infolist())
                limit = limits["max_size_mb"] * 1024 * 1024
                if total > limit:
                    return {"success": False,
                            "message": f"❌ Zip too large: {total//(1024*1024)}MB (limit: {limits['max_size_mb']}MB)"}
                z.extractall(tmp)

            html_root = _find_html_root(tmp)
            if not html_root:
                return {"success": False, "message": "❌ No <code>index.html</code> found in zip."}

            if progress_cb: progress_cb("🚀 Copying files...")
            os.makedirs(site_dir, exist_ok=True)
            for item in os.listdir(html_root):
                src = os.path.join(html_root, item)
                dst = os.path.join(site_dir, item)
                (shutil.copytree if os.path.isdir(src) else shutil.copy2)(src, dst)

        _run(f"chmod -R 755 {site_dir}")
        _run(f"chown -R www-data:www-data {site_dir}")

        if progress_cb: progress_cb("⚙️ Configuring nginx + SSL...")

        _write_nginx(site_name, _nginx_subdomain_config(subdomain, site_dir))
        ok, out = _reload_nginx()
        if not ok:
            shutil.rmtree(site_dir, ignore_errors=True)
            _remove_nginx(site_name)
            return {"success": False, "message": f"❌ Nginx error:\n<code>{out}</code>"}

        if progress_cb: progress_cb("💾 Saving record...")
        create_website_record(db, user_id, site_name, subdomain, site_dir,
                              "Premium" if is_premium else "Free")

        return {
            "success":   True,
            "url":       f"https://{subdomain}",
            "subdomain": subdomain,
            "site_name": site_name,
            "ssl":       True,
            "message":   "✅ Website deployed!",
        }
    except Exception as e:
        shutil.rmtree(site_dir, ignore_errors=True)
        _remove_nginx(site_name)
        _reload_nginx()
        return {"success": False, "message": f"❌ Deployment failed: {e}"}

def update_website(db, site_name: str, zip_path: str,
                   is_premium: bool, progress_cb=None) -> dict:
    site = get_website(db, site_name)
    if not site:
        return {"success": False, "message": "❌ Website not found."}

    limits   = get_website_limits(is_premium)
    site_dir = site["site_dir"]

    try:
        with tempfile.TemporaryDirectory() as tmp:
            with zipfile.ZipFile(zip_path, "r") as z:
                total = sum(i.file_size for i in z.infolist())
                if total > limits["max_size_mb"] * 1024 * 1024:
                    return {"success": False,
                            "message": f"❌ Zip too large. Limit: {limits['max_size_mb']}MB"}
                z.extractall(tmp)

            html_root = _find_html_root(tmp)
            if not html_root:
                return {"success": False, "message": "❌ No index.html found."}

            if progress_cb: progress_cb("🔄 Updating files...")
            shutil.rmtree(site_dir, ignore_errors=True)
            os.makedirs(site_dir, exist_ok=True)
            for item in os.listdir(html_root):
                src = os.path.join(html_root, item)
                dst = os.path.join(site_dir, item)
                (shutil.copytree if os.path.isdir(src) else shutil.copy2)(src, dst)

        _run(f"chmod -R 755 {site_dir}")
        _run(f"chown -R www-data:www-data {site_dir}")
        update_website_record(db, site_name, {})
        return {"success": True, "message": "✅ Website updated!"}
    except Exception as e:
        return {"success": False, "message": f"❌ Update failed: {e}"}

def add_custom_domain(db, site_name: str, custom_domain: str, is_premium: bool) -> dict:
    if not is_premium:
        return {"success": False,
                "message": "❌ Custom domains are <b>Premium only</b>. Use /premium to upgrade."}

    site = get_website(db, site_name)
    if not site:
        return {"success": False, "message": "❌ Website not found."}

    custom_domain = custom_domain.lower().strip().rstrip(".")
    if not re.match(r"^([a-z0-9][a-z0-9\-]*\.)+[a-z]{2,}$", custom_domain):
        return {"success": False,
                "message": "❌ Invalid domain. Example: <code>mysite.com</code>"}

    existing = db.db["websites"].find_one({"custom_domain": custom_domain})
    if existing and existing["site_name"] != site_name:
        return {"success": False, "message": "❌ Domain already linked to another site."}

    site_dir    = site["site_dir"]
    config_name = f"{site_name}--custom"

    _write_nginx(config_name, _nginx_custom_domain_config(custom_domain, site_dir))
    ok, out = _reload_nginx()
    if not ok:
        _remove_nginx(config_name)
        return {"success": False, "message": f"❌ Nginx error:\n<code>{out}</code>"}

    ssl_ok, cert, key, ssl_msg = _issue_certbot_ssl(custom_domain, site_dir)
    if ssl_ok:
        _write_nginx(config_name, _nginx_custom_domain_config(
            custom_domain, site_dir, ssl=True, cert=cert, key=key))
        _reload_nginx()

    update_website_record(db, site_name, {
        "custom_domain": custom_domain,
        "custom_ssl":    ssl_ok,
    })

    return {
        "success":     True,
        "url":         f"{'https' if ssl_ok else 'http'}://{custom_domain}",
        "ssl":         ssl_ok,
        "ssl_message": ssl_msg,
        "message":     "✅ Custom domain linked!",
    }


def remove_custom_domain(db, site_name: str) -> dict:
    site = get_website(db, site_name)
    if not site:
        return {"success": False, "message": "❌ Website not found."}
    if not site.get("custom_domain"):
        return {"success": False, "message": "❌ No custom domain linked."}
    _remove_nginx(f"{site_name}--custom")
    _reload_nginx()
    update_website_record(db, site_name, {"custom_domain": None, "custom_ssl": False})
    return {"success": True, "message": "✅ Custom domain removed."}

def delete_website(db, site_name: str) -> dict:
    site = get_website(db, site_name)
    if not site:
        return {"success": False, "message": "❌ Website not found."}

    _remove_nginx(site_name)
    if site.get("custom_domain"):
        _remove_nginx(f"{site_name}--custom")
    _reload_nginx()

    site_dir = site.get("site_dir", "")
    if site_dir and os.path.exists(site_dir):
        shutil.rmtree(site_dir, ignore_errors=True)

    delete_website_record(db, site_name)
    return {"success": True, "message": "✅ Website deleted."}

def refresh_ssl(db, site_name: str) -> dict:
    site = get_website(db, site_name)
    if not site:
        return {"success": False, "message": "❌ Website not found."}

    results = []

    ok, out = _run("sudo /usr/bin/certbot renew --cert-name teamdev.sbs-0001 --force-renewal 2>&1", timeout=180)
    results.append(f"{'✅' if ok else '❌'} Wildcard SSL (*.{BOT_DOMAIN}): {'Renewed!' if ok else out[:120]}")
    if not ok:
        results.append("⚠️ Wildcard renewal requires DNS TXT record — run certbot manually.")

    if site.get("custom_domain"):
        ok2, out2 = _run(
            f"sudo /usr/bin/certbot renew --cert-name {site['custom_domain']} --force-renewal 2>&1",
            timeout=120
        )
        results.append(f"{'✅' if ok2 else '❌'} {site['custom_domain']}: {'Renewed!' if ok2 else out2[:120]}")

    _reload_nginx()
    return {"success": True, "message": "\n".join(results)}

def get_website_status(db, site_name: str) -> dict:
    site = get_website(db, site_name)
    if not site:
        return {}

    site_dir = site.get("site_dir", "")
    size_mb  = 0
    if os.path.exists(site_dir):
        total = sum(
            os.path.getsize(os.path.join(dp, f))
            for dp, _, files in os.walk(site_dir) for f in files
        )
        size_mb = round(total / (1024 * 1024), 2)

    subdomain  = site.get("subdomain", "")
    ok, _      = _run(f"grep -rl '{subdomain}' {NGINX_SITES_DIR} 2>/dev/null")

    return {
        "site_name":     site_name,
        "subdomain":     subdomain,
        "custom_domain": site.get("custom_domain"),
        "ssl_enabled":   True,
        "custom_ssl":    site.get("custom_ssl", False),
        "status":        site.get("status", "active"),
        "size_mb":       size_mb,
        "tier":          site.get("tier", "Free"),
        "created_at":    site.get("created_at"),
        "updated_at":    site.get("updated_at"),
        "nginx_active":  ok,
    }

def _issue_certbot_ssl(domain: str, site_dir: str):
    cmd = (
        f"sudo /usr/bin/certbot certonly --webroot -w {site_dir} "
        f"--non-interactive --agree-tos --email {CERTBOT_EMAIL} "
        f"-d {domain} 2>&1"
    )
    ok, out = _run(cmd, timeout=120)
    if ok:
        cert = f"/etc/letsencrypt/live/{domain}/fullchain.pem"
        key  = f"/etc/letsencrypt/live/{domain}/privkey.pem"
        return True, cert, key, "✅ SSL issued!"
    return False, "", "", f"SSL pending — DNS may not be propagated yet. ({out[:150]})"

def validate_domain(domain: str):
    ok, out = _run(f"dig +short A {domain} | head -1", timeout=10)
    if ok and out.strip():
        return True, f"DNS resolves to: {out.strip()}"
    return False, "No A record found. Point your domain's A record to this server's IP first."

def _find_html_root(directory: str):
    if os.path.exists(os.path.join(directory, "index.html")):
        return directory
    for folder in ["dist", "build", "public", "out", "www", "html", "static"]:
        path = os.path.join(directory, folder)
        if os.path.isdir(path) and os.path.exists(os.path.join(path, "index.html")):
            return path
    for root, _, files in os.walk(directory):
        if "index.html" in files:
            return root
    return None
"""